const COLORS=['🔥','⚡','🌿','💧','🌙'];
const ENEMIES=['슬라임','고블린','그림자 늑대','수정 골렘','마왕의 파편'];
const CHAR_POOL=Array.from({length:30},(_,i)=>({id:i+1,name:['루나','카이','미라','토르','아린','제드'][i%6]+' '+(i+1),icon:['🧙','🗡️','🏹','🛡️','🦊','🐉'][i%6],rare:['N','R','SR','SSR'][Math.min(3,Math.floor(i/8))],atk:18+i*2,hp:120+i*9}));
const STAGES=Array.from({length:50},(_,i)=>({id:i+1,diff:Math.ceil((i+1)/10),time:65-Math.min(25,Math.floor(i/2)),targetHp:140+i*42,goal:i%4===0?'적 처치 + 18타일 제거':'제한 시간 내 적 처치',reward:{gold:60+i*8,exp:45+i*6,gem:i%5===0?2:0}}));
const ACH=[['first','첫 승리',1],['s10','스테이지 10 클리어',10],['s25','스테이지 25 클리어',25],['s50','50 스테이지 정복',50],['collector','캐릭터 10명 수집',10],['rich','골드 5000 보유',5000]];
const base={stage:1,gold:0,gem:0,chars:[{...CHAR_POOL[0],level:1,exp:0,sp:0}],active:1,cleared:0,stats:{wins:0,tiles:0,bestChain:0},missions:null,lastDaily:'',ach:{},tutorial:false};
let state=load(); let board=[], selected=[], dragging=false, enemy, timer=null, left=0, colorBombReady=false, tab='stages', combo=0;
const $=id=>document.getElementById(id);
function load(){try{return {...base,...JSON.parse(localStorage.getItem('chainHeroes')||'{}')}}catch(e){return structuredClone(base)}}
function save(){localStorage.setItem('chainHeroes',JSON.stringify(state));$('saveState').textContent='저장됨 '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});}
function hero(){return state.chars.find(c=>c.id===state.active)||state.chars[0]}
function needExp(l){return 90+l*45}
function today(){return new Date().toISOString().slice(0,10)}
function initDaily(){if(state.lastDaily!==today()){state.lastDaily=today();state.missions=[{id:'clear3',t:'스테이지 3회 클리어',v:0,max:3,r:'보석 3'},{id:'chain6',t:'6연결 이상 5회',v:0,max:5,r:'골드 500'},{id:'tiles80',t:'타일 80개 제거',v:0,max:80,r:'EXP 120'}];save();}}
function startStage(id=state.stage){clearInterval(timer); const s=STAGES[id-1]; left=s.time; enemy={name:ENEMIES[id%ENEMIES.length],hp:s.targetHp,max:s.targetHp,def:s.diff*2,icon:['👾','👹','🐺','🗿','😈'][id%5]}; board=Array.from({length:36},()=>tile()); colorBombReady=false; selected=[]; renderAll(); timer=setInterval(()=>{left--; $('timeLeft').textContent=left; if(left<=0) end(false,'시간 초과');},1000)}
function tile(){return {c:Math.floor(Math.random()*COLORS.length),p:null}}
function renderAll(){initDaily(); renderBattle(); renderBoard(); renderProfile(); renderPanel(); checkAch();}
function renderBattle(){let s=STAGES[state.stage-1];$('stageName').textContent=`Stage ${s.id} · 난이도 ${s.diff}`;$('stageGoal').textContent=s.goal;$('timeLeft').textContent=left;$('enemyName').textContent=enemy.name;$('enemyAvatar').textContent=enemy.icon;$('enemyHp').textContent=Math.max(0,enemy.hp)+' / '+enemy.max;$('enemyDef').textContent=enemy.def;$('enemyHpBar').style.width=Math.max(0,enemy.hp/enemy.max*100)+'%';$('colorBomb').disabled=!colorBombReady;}
function renderProfile(){const h=hero();$('heroIcon').textContent=h.icon;$('heroName').textContent=h.name;$('heroLevel').textContent=h.level;$('heroExp').textContent=h.exp;$('needExp').textContent=needExp(h.level);$('atk').textContent=h.atk+h.level*5;$('hp').textContent=h.hp+h.level*15;$('gold').textContent=state.gold;$('gem').textContent=state.gem;}
function renderBoard(){const b=$('board'); b.innerHTML=''; board.forEach((t,i)=>{let d=document.createElement('div'); d.className=`tile t${t.c} ${selected.includes(i)?'sel':''} ${t.p?'power':''}`; d.dataset.i=i; d.textContent=t.p?powerIcon(t.p):COLORS[t.c]; d.addEventListener('pointerdown',e=>begin(i,e)); d.addEventListener('pointerenter',()=>move(i)); d.addEventListener('pointerup',finish); b.appendChild(d);});}
function powerIcon(p){return {line:'💥',area:'💣',color:'🌈',chain:'🔗'}[p]}
function begin(i,e){e.preventDefault(); dragging=true; selected=[i]; renderBoard();}
function move(i){if(!dragging||selected.includes(i))return; const last=selected.at(-1); if(adj(last,i)&&board[i].c===board[last].c){selected.push(i); renderBoard(); $('chainText').textContent=`${selected.length} 연결 중`;}}
function finish(){if(!dragging)return; dragging=false; if(selected.length>=3) resolveChain(); else {selected=[];renderBoard();}}
function adj(a,b){let ax=a%6,ay=Math.floor(a/6),bx=b%6,by=Math.floor(b/6);return Math.abs(ax-bx)+Math.abs(ay-by)===1}
function resolveChain(){let count=selected.length, removed=new Set(selected); let pwr=selected.map(i=>board[i].p).filter(Boolean); pwr.forEach(p=>applyPower(p,selected.at(-1),removed)); let h=hero(); let dmg=Math.max(1,(h.atk+h.level*5)*count + removed.size*8 - enemy.def); combo++; if(count>=6) incMission('chain6',1); if(count>=10) colorBombReady=true; else if(count>=8) board[selected.at(-1)]={c:board[selected.at(-1)].c,p:'area'}; else if(count>=6) board[selected.at(-1)]={c:board[selected.at(-1)].c,p:'line'}; if(combo>=3){let r=Math.floor(Math.random()*36); board[r].p='chain'} enemy.hp-=dmg; state.stats.tiles+=removed.size; state.stats.bestChain=Math.max(state.stats.bestChain,count); incMission('tiles80',removed.size); floatText('-'+dmg); removed.forEach(i=>{if(!board[i].p || selected.includes(i)) board[i]=tile()}); selected=[]; $('chainText').textContent=`${count}연결! ${removed.size}개 제거 · ${dmg} 피해`; if(enemy.hp<=0) end(true,'적 처치'); renderAll(); save();}
function applyPower(p,idx,set){let x=idx%6,y=Math.floor(idx/6); if(p==='line'){for(let i=0;i<6;i++){set.add(y*6+i);set.add(i*6+x)}} if(p==='area'){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){let nx=x+dx,ny=y+dy;if(nx>=0&&nx<6&&ny>=0&&ny<6)set.add(ny*6+nx)}} if(p==='chain'){[idx-7,idx-6,idx-5,idx-1,idx+1,idx+5,idx+6,idx+7].forEach(n=>{if(n>=0&&n<36)set.add(n)})}}
function useColorBomb(){if(!colorBombReady)return; let counts=[0,0,0,0,0]; board.forEach(t=>counts[t.c]++); let c=counts.indexOf(Math.max(...counts)); selected=board.map((t,i)=>t.c===c?i:null).filter(i=>i!==null); colorBombReady=false; resolveChain(); left=Math.min(left+3,(STAGES[state.stage-1].time));}
function end(win,reason){clearInterval(timer); timer=null; combo=0; if(win){let s=STAGES[state.stage-1], h=hero(); state.gold+=s.reward.gold; state.gem+=s.reward.gem; h.exp+=s.reward.exp; while(h.exp>=needExp(h.level)){h.exp-=needExp(h.level);h.level++;h.sp=(h.sp||0)+1; toast(`레벨업! ${h.name} Lv.${h.level}`)} state.cleared=Math.max(state.cleared,state.stage); state.stage=Math.min(50,state.stage+1); state.stats.wins++; incMission('clear3',1); if(Math.random()<.22&&state.chars.length<CHAR_POOL.length){let n=CHAR_POOL.find(c=>!state.chars.some(x=>x.id===c.id)); state.chars.push({...n,level:1,exp:0,sp:0}); toast('새 캐릭터 획득: '+n.name)} save(); setTimeout(()=>startStage(state.stage),850); toast(`클리어! ${s.reward.gold}G EXP ${s.reward.exp}`)} else {toast('실패: '+reason); setTimeout(()=>startStage(state.stage),900)} renderAll();}
function incMission(id,n){initDaily(); let m=state.missions?.find(x=>x.id===id); if(m)m.v=Math.min(m.max,m.v+n)}
function claimMission(id){let m=state.missions.find(x=>x.id===id); if(!m||m.v<m.max)return; if(id==='clear3')state.gem+=3; if(id==='chain6')state.gold+=500; if(id==='tiles80')hero().exp+=120; m.v=0;m.max+=999;toast('미션 보상 수령');save();renderAll();}
function checkAch(){ACH.forEach(a=>{if(state.ach[a[0]])return; let ok=a[0].startsWith('s')?state.cleared>=a[2]:a[0]==='first'?state.stats.wins>=1:a[0]==='collector'?state.chars.length>=10:state.gold>=5000; if(ok){state.ach[a[0]]=true; state.gem+=5; toast('업적 달성: '+a[1]); save();}})}
function renderPanel(){const p=$('panel'); p.innerHTML=''; let box=document.createElement('div'); box.className='list'; if(tab==='stages') STAGES.forEach(s=>box.append(row(`Stage ${s.id}`,`${s.goal} · 보상 ${s.reward.gold}G`,s.id<=state.cleared+1?'입장':'잠김',()=>{if(s.id<=state.cleared+1){state.stage=s.id;startStage(s.id);}}))); if(tab==='chars') state.chars.forEach(c=>box.append(row(`${c.icon} ${c.name}`,`${c.rare} · Lv.${c.level} · ATK ${c.atk+c.level*5}`,c.id===state.active?'편성중':'편성',()=>{state.active=c.id;save();renderAll();}))); if(tab==='missions') state.missions.forEach(m=>box.append(row(m.t,`${m.v}/${m.max} · ${m.r}`,m.v>=m.max?'수령':'진행중',()=>claimMission(m.id)))); if(tab==='achieve') ACH.forEach(a=>box.append(row(a[1],state.ach[a[0]]?'완료 · 보석 보상 지급':'미달성','🏆',()=>{}))); p.append(box);}
function row(t,s,b,fn){let r=document.createElement('div');r.className='row';r.innerHTML=`<div><b>${t}</b><small>${s}</small></div><button class="badge">${b}</button>`;r.querySelector('button').onclick=fn;return r}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function floatText(txt){let d=document.createElement('div');d.className='damage';d.textContent=txt;d.style.left='50%';d.style.top='32%';document.body.append(d);setTimeout(()=>d.remove(),750)}
function tutorial(){const steps=['1) 같은 색 타일을 3개 이상 4방향으로 드래그하면 공격합니다.','2) 길게 연결할수록 피해량과 콤보가 커집니다.','3) 6개 이상은 직선 폭발, 8개 이상은 범위 폭발, 10개 이상은 색 제거가 열립니다.','4) 스킬 재배치/회복으로 보드를 유리하게 바꾸세요.','5) 제한 시간 안에 적을 처치하면 보상과 EXP를 얻습니다.']; let i=0; const m=$('tutorial'); if(state.tutorial)m.classList.remove('show'); function draw(){ $('tutText').textContent=steps[i]; } draw(); $('nextTut').onclick=()=>{i++; if(i>=steps.length){state.tutorial=true;save();m.classList.remove('show')} else draw();}; $('skipTut').onclick=()=>{state.tutorial=true;save();m.classList.remove('show')}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));renderPanel();});
$('skillShuffle').onclick=()=>{board.sort(()=>Math.random()-.5);state.gem=Math.max(0,state.gem-1);toast('보드 재배치');renderBoard();save()};
$('skillHeal').onclick=()=>{left+=5;toast('시간 +5초');renderBattle()};
$('colorBomb').onclick=useColorBomb;
$('btnReset').onclick=()=>{if(confirm('저장 데이터를 초기화할까요?')){localStorage.removeItem('chainHeroes');location.reload();}};
document.addEventListener('pointerup',finish); window.addEventListener('online',()=>toast('온라인 복귀')); window.addEventListener('offline',()=>toast('오프라인 모드: 로컬 저장'));
tutorial(); startStage(state.stage);
